mysite/discovery/urls.py
from django.conf.urls import url
from . import views


app_name = 'discovery'
urlpatterns = [
    url(r'^$', views.login_user, name='login_user'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^projects/$', views.projects, name='projects'),
    url(r'^project/(?P<pk>\d+)/$', views.ProjectView.as_view(), name='project'),
    url(r'^datasets/$', views.datasets, name='datasets'),
    url(r'^daatset/(?P<pk>\d+)/$', views.DatasetView, name='dataset'),
    url(r'^save/$', views.save_aqi, name='save'),
    url(r'^load/$', views.load_aqi, name='load'),
]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^discovery/', include('discovery.urls')),
]

mysite/polls/urls.py
from django.conf.urls import url
from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^date$', views.date)
]

mysite/discovery/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from .sparks import Spark


class Project(models.Model):
    user = models.ForeignKey(User, default=1)
    name = models.CharField(max_length=200)
    created_time = models.DateTimeField('date created')

    def __str__(self):
        return self.name


class Dataset(models.Model):
    user = models.ForeignKey(User, default=1)
    name = models.CharField(max_length=200)
    creator = models.CharField(max_length=200)
    created_time = models.DateTimeField('date created')
    attributes = models.TextField()

    def __str__(self):
        return self.name


class Collection(object):
    def __init__(self, collection_name):
        self._collection = collection_name
        self._sc = Spark()

    def to_spark(self):
        sql = 'SELECT * FROM ' + self._collection
        return self._sc.spark.sql(sql)


class AQI(object):
    def __init__(self):
        self._sc = Spark()

    def save_aqi(self):
        dataset_cols = ['name', 'creator', 'created_time', 'attributes']
        ds = Dataset()
        ds.name = 'aqi'
        ds.creator = 'walt'
        ds.created_time = timezone.now()
        ds.attributes = 'location||date||aqi'
        ds.save()
        # datasets = [('aqi', 'walt', '2017-01-03', 'location||date||aqi'), ]
        # rdd = self._sc.spark.sparkContext.parallelize(datasets)
        # df1 = self._sc.spark.createDataFrame(rdd, dataset_cols)
        # df1 = df1.withColumn('created_time', df1.created_time.cast('timestamp').alias('created_time'))
        # list = [{'name': 'Alice', 'id': 1}, {'name': 'Bob', 'id': 2}, {'name': 'Peter', 'id': 3}]
        # df = self._sc.spark.createDataFrame(list)
        # df1.write.saveAsTable('mdr')
        aqi = [('Shanghai', '2017-01-02', 100),]
        df2 = self._sc.spark.createDataFrame(aqi, ['location', 'date', 'aqi'])
        df2.write.saveAsTable('aqi')

    def load_aqi(self, query=None):
        string = 'SELECT * FROM AQI'
        if query is not None:
            string += ' ' + query
        df = self._sc.spark.sql(string)
        return df

mysite/discovery/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.db.models.query_utils import Q
from django.contrib.auth import authenticate, login, logout
from .models import Project, Dataset, Collection
from .forms import UserForm
from .models import AQI
from django.http import HttpResponse


def load_aqi(request):
    aqi = AQI()
    df = aqi.load_aqi()
    return HttpResponse(df.dtypes)


def save_aqi(request):
    aqi = AQI()
    aqi.save_aqi()
    return HttpResponse('Saved')


class ProjectsView(generic.ListView):
    template_name = 'discovery/projects.html'
    context_object_name = 'project_list'

    def get_queryset(self):
        return Project.objects.all()


class ProjectView(generic.DetailView):
    template_name = 'discovery/project.html'
    model = Project


class DatasetView(generic.DetailView):
    model =Dataset


def datasets(request):
    if not request.user.is_authenticated():
        return render(request, 'discovery/login.html')
    else:
        # aqi = AQI()
        # dss = aqi.load_aqi().collect()
        # dataset_list = [ds.asDict() for ds in dss]
        dataset_list = Dataset.objects.filter(user=request.user)
        return render(request, 'discovery/datasets.html', {
            'datasets': dataset_list,
        })


def dataset(request, pk):
    if not request.user.is_authenticated():
        return render(request, 'discovery/dataset.html')
    else:
        ds = get_object_or_404(Dataset, pk=pk)
        collection = Collection(ds.name)
        column_titles = [attribute.strip() for attribute in ds.attributes.split('||')]
        df = collection.to_spark()
        rows = []
        for row in df.collect():
            data = {}
            for k, v in row.asDict().items():
                data[k] = v
            rows.append(data)
        return render(request, 'discovery/dataset.html', {
            'dataset': dataset,
            'column_titles': column_titles,
            'column_body': rows,
        })


def projects(request):
    if not request.user.is_authenticated():
        return render(request, 'discovery/login.html')
    else:
        project_list = Project.objects.filter(user=request.user)
        query = request.GET.get('q')
        if query:
            project_list = project_list.filter(Q(name__icontains=query)).distinct()
            return render(request, 'discovery/projects.html', {
                'projects': project_list,
            })
        else:
            return render(request, 'discovery/projects.html', {
                'projects': project_list,
            })


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                project_list = Project.objects.filter(user=request.user)
                return render(request, 'discovery/projects.html', {'projects': project_list})
            else:
                return render(request, 'discovery/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'discovery/login.html', {'error_message': 'Invalid login'})
    return render(request, 'discovery/login.html')


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                project_list = Project.objects.filter(user=request.user)
                return render(request, 'discovery/index.html', {'projects': project_list})
    context = {
        "form": form,
    }
    return render(request, 'discovery/register.html', context)


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'discovery/login.html', context)

mysite/discovery/templates/discovery/base.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}discovery{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'discovery/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'discovery/js/main.js' %}"></script>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">

            <!-- Header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'discovery:projects' %}">Discovery</a>
            </div>

            <!-- Items -->
            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <li class="{% block project_active %}{% endblock %}">
                        <a href="{% url 'discovery:projects' %}">
                            <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>&nbsp; Projects
                        </a>
                    </li>
                    <li class="{% block dataset_active %}{% endblock %}">
                        <a href="{% url 'discovery:projects' %}">
                            <span class="glyphicon glyphicon-th-large" aria-hidden="true"></span>&nbsp; DataSets
                        </a>
                    </li>
                </ul>
                <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'discovery:projects' %}">
                    <div class="form-group">
                        <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                    </div>
                    <button type="submit" class="btn bk-bs-btn-default">Search</button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'discovery:projects' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Project
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'discovery:login_user' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% block body %}
    {% endblock %}
</body>
</html>

mysite/discovery/templates/discovery/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Discovery{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'discovery/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'discovery/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'discovery:projects' %}">Discovery</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'discovery:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'discovery:login_user' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

mysite/discovery/templates/discovery/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="dataset_name">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

mysite/discovery/templates/discovery/login.html
{% extends 'discovery/base_visitor.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'discovery:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'discovery:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}


mysite/discovery/templates/discovery/project.html
{% extends 'discovery/base.html' %}
{% block project_active %}active{% endblock %}

{% block body %}
<h1>{{ project.name }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<table class="table table-striped">
    <thead>
        <tr>
            <td>Name</td>
            <td>Creator</td>
            <td>Date</td>
        </tr>
    </thead>
{% for dataset in project.dataset_set.all %}
    <tbody>
        <tr>
            <td>{{ dataset.name }}</td>
            <td>{{ dataset.creator }}</td>
            <td>{{ dataset.creation_date }}</td>
        </tr>
    </tbody>
{% endfor %}
</table>
{% endblock %}

mysite/discovery/templates/discovery/projects.html
{% extends 'discovery/base.html' %}
{% block project_active %}active{% endblock %}

{% block body %}
    <div class="albums-container container-fluid">

        <!-- Projects -->
        <div class="row">
            <div class="col-sm-12">
                <h3>{{ user.username }}'s Projects</h3>
            </div>
            {% if projects %}
                <ul>
                    {% for project in projects %}
                        <div class="col-sm-4 col-lg-2">
                            <div class="thumbnail">
                                <a href="{% url 'discovery:project' project.id %}">
                                    <img src="#" class="img-responsive" >
                                </a>
                                <div class="caption">
                                    <h2>{{ project.name }}</h2>
                                    <h4>{{ project.creation_date }}</h4>

                                    <!-- View Details -->
                                    <a href="{% url 'discovery:project' project.id %}" class="btn btn-primary btn-sm" role="button">View Project</a>

                                    <!-- Delete Album -->
                                    <form action="#" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="project_id" value="{{ project.id }}" />
                                        <button type="submit" class="btn btn-default btn-sm">
                                            <span class="glyphicon glyphicon-trash"></span>
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </div>
                        {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
                    {% endfor %}
                </ul>
            {% else %}
                <div class="col-sm-12">
                    <br>
                    <a href="{% url 'discovery:projects' %}">
                        <button type="button" class="btn btn-success">
                            <span class="glyphicon glyphicon-plus"></span>&nbsp; Add a Project
                        </button>
                    </a>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

mysite/discovery/templates/discovery/register.html
{% extends 'discovery/base_visitor.html' %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'discovery/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'discovery:login_user' %}">Click here</a> to log in.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}
