mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^discovery/', include('discovery.urls')),
]

mysite/polls/urls.py
from django.conf.urls import url
from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^date$', views.date)
]

mysite/stocks/urls.py
from django.conf.urls import url
from . import views

app_name = 'stocks'

urlpatterns = [
    url(r'^$', views.InvestmentView.as_view(), name='investments'),
    url(r'^(?P<pk>\d+)/$', views.StockView.as_view(), name='stock'),
    url(r'^(?P<code>.*?)/wait/$', views.WaitingView.as_view(), name='waiting'),
    url(r'^(?P<pk>\d+)/delete/$', views.InvestmentDelete.as_view(), name='delete'),
    url(r'^logout_user/$', views.LogoutView.as_view(), name='logout_user'),
]

mysite/stocks/models.py
from django.db import models
from django.contrib.auth.models import User


class InvestmentModel(models.Model):
    user = models.ForeignKey(User)
    code = models.CharField(max_length=10)

    def __str__(self):
        return self.code

    def __repr__(self):
        return self.code


class StockModel(models.Model):
    investment = models.ForeignKey(InvestmentModel)
    code = models.CharField(max_length=10)
    date = models.DateField()
    open = models.FloatField()
    high = models.FloatField()
    low = models.FloatField()
    close = models.FloatField()
    volume = models.BigIntegerField()
    adj_close = models.FloatField()

    def __str__(self):
        return self.code + ' : ' + self.date.strftime('%b %d %Y')

    def __repr__(self):
        return self.code + ' : ' + self.date.strftime('%b %d %Y')

mysite/stocks/forms.py
from django import forms


class StockForm(forms.Form):
    code = forms.CharField(max_length=10, label='Stock Code')

mysite/stocks/views.py
from django.core.urlresolvers import reverse_lazy
from django.views.generic.detail import SingleObjectMixin
from django.views.generic import ListView, TemplateView, View
from django.views.generic.edit import DeleteView
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth import authenticate, login, logout
from .models import InvestmentModel
from .provision import create_investment


class InvestmentView(ListView):
    template_name = 'stocks/stocks.html'
    context_object_name = 'investment_list'

    def get_queryset(self):
        return InvestmentModel.objects.filter(user__username=self.request.user.username)

    def get(self, request, *args, **kwargs):
        if request.GET.get('stock_code'):
            try:
                investment = InvestmentModel.objects.get(code=request.GET.get('stock_code'))
            except ObjectDoesNotExist:
                return render(request, 'stocks/waiting.html', {'code': request.GET.get('stock_code')})
                # return redirect('stocks:waiting', code=request.GET.get('stock_code'))
            else:
                return redirect('stocks:stock', pk=investment.id)
        return super(InvestmentView, self).get(request, *args, **kwargs)


class StockView(SingleObjectMixin, ListView):
    template_name = 'stocks/stock.html'
    context_object_name = 'stock_list'
    paginate_by = 30

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=InvestmentModel.objects.all())
        return super(StockView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(StockView, self).get_context_data(**kwargs)
        context['investment'] = self.object
        return context

    def get_queryset(self):
        return self.object.stockmodel_set.all()


class InvestmentDelete(DeleteView):
    model = InvestmentModel
    success_url = reverse_lazy('stocks:investments')


class WaitingView(TemplateView):
    template_name = 'stocks/waiting.html'

    def get(self, request, *args, **kwargs):
        try:
            investment = create_investment(code=kwargs.get('code'), user=request.user)
        except Exception as e:
            messages.add_message(request, messages.INFO, 'Can not find stock with code: {}'.format(kwargs.get('code')))
        #     return render(request, 'stocks/waiting.html', )
            return super(WaitingView, self).get(request, *args, **kwargs)
        return redirect('stocks:stock', pk=investment.id)


class LogoutView(View):
    def get(self, request, *args, **kwargs):
        logout(request)

mysite/stocks/templates/stocks/base.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}stocks{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'stocks/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.js"></script>
    <script src="http://canvasjs.com/assets/script/canvasjs.min.js"></script>
    <script src="{% static 'stocks/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'stocks:investments' %}">Stocks</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="">
                    <a href="{% url 'stocks:investments' %}">
                        <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>&nbsp; Stocks
                    </a>
                </li>
            </ul>

            <form class="navbar-form navbar-left" method="get" action="{% url 'stocks:investments' %}">
                <div class="input-group">
                    <input id="stock_code" name="stock_code" class="form-control" placeholder="stock code">
                    <div class="input-group-btn">
                        <button type="submit" value="Search" class="btn btn-default">
                            <i class="glyphicon glyphicon-search"></i>
                        </button>
                    </div>
                </div>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'stocks:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

mysite/stocks/templates/stocks/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

mysite/stocks/templates/stocks/investmentmodel_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New</title>
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'stocks/form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

mysite/stocks/templates/stocks/stock.html
{% extends 'stocks/base.html' %}
{% block body %}
    <div class="container-fluid" style="padding-top: 70px">
        <div class="row">
            <div class="col-sm-4 col-sm-3">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h2>Investment {{ investment.code }}</h2>
                        <form action="{% url 'stocks:delete' investment.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-default btn-sm">
                                <span class="glyphicon glyphicon-trash"></span>
                            </button>
                        </form>
                        <a class="btn-default" href="{% url 'stocks:investments' %}">Back</a>
                    </div>
                </div>
            </div>
            <div class="col-sm-8 col-sm-9">
                <div class="panel panel-default">
                <div id="section1" class="container-fluid">
                    <div class="pagination">
                            <span class="step-links">
                                {% if page_obj.has_previous %}
                                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                                {% endif %}
                                <span class="current">
                                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                                </span>
                                {% if page_obj.has_next %}
                                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                                {% endif %}
                            </span>
                    </div>

                    <div style="height: 450px; overflow-y: scroll;">
                        <table class="table table-striped table-hover table-bordered">
                            <thead>
                                <tr>
                                    <td>date</td>
                                    <td>open</td>
                                    <td>high</td>
                                    <td>low</td>
                                    <td>close</td>
                                    <td>volume</td>
                                    <td>adjusted close</td>
                                </tr>
                            </thead>
                            <tbody>
                            {% for stock in page_obj %}
                                <tr>
                                    <td>{{ stock.date }}</td>
                                    <td>{{ stock.open }}</td>
                                    <td>{{ stock.high }}</td>
                                    <td>{{ stock.low }}</td>
                                    <td>{{ stock.close }}</td>
                                    <td>{{ stock.volume }}</td>
                                    <td>{{ stock.adj_close }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>

                    <div class="pagination">
                            <span class="step-links">
                                {% if page_obj.has_previous %}
                                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                                {% endif %}
                                <span class="current">
                                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                                </span>
                                {% if page_obj.has_next %}
                                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                                {% endif %}
                            </span>
                        </div>
                </div>
                <br>
                <div id="section2" class="container-fluid">
                    <div class="row">
                        <div class="col-sm-4">
                            <canvas id="chartContainer1" style="height: 500px; width: 100%;">
                                Hello
                            </canvas>
                        </div>
                        <div class="col-sm-4">
                            <canvas id="chartContainer2" style="height: 500px; width: 100%;">
                                World
                            </canvas>
                        </div>
                        <div class="col-sm-4">
                            <canvas id="chartContainer3" style="height: 500px; width: 100%;">
                                Again
                            </canvas>
                        </div>
                    </div>
                </div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        window.onload = function () {
            var options = {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero:true
                        }
                    }]
                }
            }
            var ctx = document.getElementById("chartContainer1");
            var myChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: [
                        {% for stock in page_obj %}
                            '{{ stock.date }}',
                        {% endfor %}
                    ],
                    datasets: [{
                        label: 'Volume',
                        data: [
                            {% for stock in page_obj %}
                                {{ stock.volume }},
                            {% endfor %}
                        ],
                        backgroundColor: [
                            {% for stock in page_obj %}
                                'rgba(126, 215, 126, 1)',
                            {% endfor %}
                        ]
                    }]
                },
                options: options
            });

            var ctx = document.getElementById("chartContainer2");
            var myChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: [
                        {% for stock in page_obj %}
                            '{{ stock.date }}',
                        {% endfor %}
                    ],
                    datasets: [{
                        label: 'Adjust Close',
                        data: [
                            {% for stock in page_obj %}
                                {{ stock.adj_close }},
                            {% endfor %}
                        ],
                        backgroundColor: [
                            {% for stock in page_obj %}
                            'rgba({% widthratio forloop.counter 1 5 %}, {% widthratio forloop.counter 1 5 %}, {% widthratio forloop.counter 1 5 %}, 1)',
                            {% endfor %}
                        ]
                    }]
                },
                options: options
            });

            var ctx = document.getElementById("chartContainer3");
            var myChart = new Chart(ctx, {
                type: 'line',
                data: {
                    labels: [
                        {% for stock in page_obj %}
                            '{{ stock.date }}',
                        {% endfor %}
                    ],
                    datasets: [{
                        label: 'Close',
                        data: [
                            {% for stock in page_obj %}
                                {{ stock.close }},
                            {% endfor %}
                        ],
                        backgroundColor: 'rgba(0, 60, 126, 0.5)',
                    }],
                    fill: false,
                    lineTension: 0.1,
                    borderCapStyle: 'butt',
                    borderDash: [],
                    borderDashOffset: 0.0,
                    borderJoinStyle: 'miter',
                },
                options: options
            });
        }
    </script>
{% endblock %}

mysite/stocks/templates/stocks/stocks.html
{% extends 'stocks/base.html' %}
{% block body %}
    <div class="col-sm-4 col-lg-2" style="padding-top: 70px;">
    {% if messages %}
        {% for message in messages %}
        <p><strong>{{ message }}</strong></p>
        {% endfor %}
    {% endif %}
        <div class="container">
            <div class="row">
            {% if investment_list %}
                {% for investment in investment_list %}
                <div class="col-sm-3">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            {{ investment.code }}
                        </div>
                        <div class="panel-body">
                            <a href="/stocks/{{ investment.id }}">Detail</a>
                        </div>
                        <div class="panel-footer">
                            <form action="{% url 'stocks:delete' investment.id %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
                {% endfor %}
            {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

mysite/stocks/templates/stocks/waiting.html
<head>
    <meta charset="UTF-8">
    <title>{% block title %}discovery{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'stocks/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'stocks/js/main.js' %}"></script>
    <script>
        $(document).ready(function () {
                $.ajax({
                    url: "{% url 'stocks:waiting' code %}",
                    complete: function (xhr, status) {
                        if (status == 'success') {
                            location.reload();
                            return;
                        }
                        window.location.replace('/stocks/');
                    },
                })
            },
            setInterval(function() {
                $("#dot1").after(".");
            }, 1000)
        )
    </script>
</head>

<body>
<span id="dot1">Waiting</span>
</body>